import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const Q = (skill, text, opts, ans, diff) => ({
  skillName: skill,
  questionText: text,
  options: opts,
  correctAnswer: opts[ans],
  difficulty: diff,
  questionType: "multiple-choice",
  explanation: `The correct answer is: ${opts[ans]}`
});

const writeFile = (filename, roleName, skills, questions) => {
  const dataDir = path.join(__dirname, '..', 'data');
  const filePath = path.join(dataDir, filename);
  const content = `// ${roleName} Questions\n// Skills: ${skills.join(', ')}\n// Total: ${questions.length} questions\n\nexport const ${filename.replace('.js', '')} = ${JSON.stringify(questions, null, 2)};\n`;
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`✅ ${roleName}: ${questions.length} questions`);
};

console.log("🚀 Generating final 4 roles (300 questions)...\n");

// ROLE 5: AI/ML ENGINEER
const aiMlEngineerQuestions = [
  Q("Python","Which library is most used for numerical computation in Python?",["TensorFlow","NumPy","Pandas","Matplotlib"],1,"basic"),
  Q("Python","Which Python library is best for data manipulation?",["Flask","SciPy","Pandas","Selenium"],2,"basic"),
  Q("Python","Which function is used to check data type of a variable?",["dtype()","class()","isinstance()","type()"],3,"basic"),
  Q("Python","What is the output of len([1,2,3,4])?",["3","5","2","4"],3,"basic"),
  Q("Python","Which keyword defines a class in Python?",["struct","class","define","object"],1,"basic"),
  Q("Python","What does the iloc method in Pandas do?",["Accesses rows/columns by index positions","Groups data","Removes missing values","Selects data by label"],0,"intermediate"),
  Q("Python","What function reads CSV files in Pandas?",["read_csv()","csv_reader()","load()","import_csv()"],0,"intermediate"),
  Q("Python","Which Python library provides statistical and scientific tools?",["Flask","Seaborn","SciPy","Matplotlib"],2,"intermediate"),
  Q("Python","What is the output of np.zeros((2,2))?",["List of two None values","2x2 matrix of zeros","Empty list","Error"],1,"intermediate"),
  Q("Python","What is a DataFrame?",["Two-dimensional labeled data structure","Database schema","File object","Single list"],0,"intermediate"),
  Q("Python","What is a lambda function?",["Anonymous function defined in one line","Function with static type","Function without return","Class method"],0,"advanced"),
  Q("Python","What is the purpose of @property decorator?",["Converts method into read-only attribute","Defines static variable","Makes variable public","Creates hidden class"],0,"advanced"),
  Q("Python","What is the difference between shallow copy and deep copy?",["Deep copy duplicates nested objects; shallow only references them","Deep copy removes references","Shallow copy is immutable","Both are same"],0,"advanced"),
  Q("Python","What is the time complexity of searching in a Python dictionary?",["O(1) average case","O(n) always","O(log n)","O(n²)"],0,"advanced"),
  Q("Python","Which module in Python handles serialization?",["marshal","pickle","csv","json"],1,"advanced"),
  Q("TensorFlow","TensorFlow is a library for?",["Database management","Machine Learning and Deep Learning","Web scraping","Game development"],1,"basic"),
  Q("TensorFlow","TensorFlow is developed by?",["Meta","Google","OpenAI","Microsoft"],1,"basic"),
  Q("TensorFlow","What is a tensor?",["Multi-dimensional array used in ML models","String variable","Random function","Single scalar value"],0,"basic"),
  Q("TensorFlow","What command installs TensorFlow?",["conda make tensorflow","pip install tensorflow","npm install tensorflow","install tf"],1,"basic"),
  Q("TensorFlow","What is the file extension for TensorFlow models?",[".csv",".json",".h5",".pkl"],2,"basic"),
  Q("TensorFlow","What does Keras API do?",["Provides high-level neural network interface for TensorFlow","Manages data preprocessing","Stores tensors","Visualizes graphs"],0,"intermediate"),
  Q("TensorFlow","What is TensorBoard used for?",["Visualizing training metrics like loss and accuracy","Managing hardware","Cleaning datasets","Generating random tensors"],0,"intermediate"),
  Q("TensorFlow","What is the purpose of an optimizer?",["Minimizes the loss function during training","Stores checkpoints","Increases learning rate","Scales input data"],0,"intermediate"),
  Q("TensorFlow","Which layer type is used in convolutional networks?",["Dropout","RNN","Dense","Conv2D"],3,"intermediate"),
  Q("TensorFlow","What does the dropout layer do?",["Adds noise","Increases neuron connections","Prevents overfitting by randomly disabling neurons","Reduces input data"],2,"intermediate"),
  Q("TensorFlow","What is a gradient tape used for?",["Automatic differentiation to compute gradients","Creating variables","Normalizing inputs","Saving model architecture"],0,"advanced"),
  Q("TensorFlow","What is eager execution in TensorFlow?",["Immediate evaluation of operations without building a graph","GPU offloading","Lazy loading","Batch mode processing"],0,"advanced"),
  Q("TensorFlow","What is the difference between static and dynamic computation graphs?",["Dynamic graphs allow runtime modification; static graphs don't","Static graphs are faster","Dynamic graphs can't use GPUs","Both are same"],0,"advanced"),
  Q("TensorFlow","What is TensorFlow Lite used for?",["Compressing datasets","Encrypting tensors","Deploying ML models on mobile or edge devices","Creating GUIs"],2,"advanced"),
  Q("TensorFlow","What is TensorFlow Serving?",["Model deployment system for production","Preprocessing module","Data visualization tool","Error handler"],0,"advanced"),
  Q("PyTorch","PyTorch is primarily used for?",["File compression","Deep Learning model building","Cloud infrastructure","Frontend development"],1,"basic"),
  Q("PyTorch","PyTorch is developed by?",["IBM","Meta (Facebook)","Google","OpenAI"],1,"basic"),
  Q("PyTorch","What function converts a NumPy array to a tensor?",["torch.tensorize()","torch.as_array()","torch.from_numpy()","numpy.to_tensor()"],2,"basic"),
  Q("PyTorch","What command installs PyTorch?",["install pytorch","pip install torch","npm install torch","conda torch install"],1,"basic"),
  Q("PyTorch","What is autograd in PyTorch?",["Automatic differentiation engine","Optimizer","Gradient normalizer","Activation layer"],0,"basic"),
  Q("PyTorch","What is nn.Module?",["Loss function","Base class for all neural network models","Optimizer","Data loader"],1,"intermediate"),
  Q("PyTorch","What does DataLoader do?",["Loads data in batches for training","Downloads datasets","Visualizes results","Preprocesses text"],0,"intermediate"),
  Q("PyTorch","What optimizer implements gradient descent?",["torch.optim.SGD","torch.update.GD","torch.grad.Descent","torch.optimize.Adam"],0,"intermediate"),
  Q("PyTorch","What does backward() method do?",["Computes gradients of tensors","Reverses layers","Initializes weights","Saves model"],0,"intermediate"),
  Q("PyTorch","What does model.eval() do?",["Sets model to evaluation mode (disables dropout, etc.)","Trains model","Deletes tensors","Resets gradients"],0,"intermediate"),
  Q("PyTorch","What is torchscript used for?",["Serializing and optimizing PyTorch models for deployment","Creating dynamic graphs","GPU testing","Saving datasets"],0,"advanced"),
  Q("PyTorch","What is the difference between CPU and GPU tensor operations?",["GPU tensors run on CUDA for parallel computation","GPU tensors use RAM only","CPU is faster","No difference"],0,"advanced"),
  Q("PyTorch","What is the purpose of torch.no_grad()?",["Disables gradient tracking for inference","Deletes weights","Normalizes input","Enables dropout"],0,"advanced"),
  Q("PyTorch","What is a custom dataset class used for?",["Loading and preprocessing user-defined datasets","Freezing parameters","Visualizing training","Saving metrics"],0,"advanced"),
  Q("PyTorch","What does state_dict contain?",["Model parameters and optimizer state","Dataset metadata","Graph structure","Error log"],0,"advanced"),
  Q("Deep Learning","What is a neural network?",["System of interconnected nodes that mimic human brain behavior","Simple loop","Database system","File storage"],0,"basic"),
  Q("Deep Learning","What is an epoch?",["Activation output","Dropout ratio","One complete pass through the training dataset","Number of hidden layers"],2,"basic"),
  Q("Deep Learning","What is a neuron?",["Basic unit that receives, processes, and transmits signals in a network","Loss function","Variable","Data structure"],0,"basic"),
  Q("Deep Learning","What is backpropagation?",["Algorithm used to adjust weights by minimizing errors","Data shuffling","Forward pass process","Layer initialization"],0,"basic"),
  Q("Deep Learning","What is an activation function?",["Adds non-linearity to neural networks","Tracks gradients","Normalizes data","Stores weights"],0,"basic"),
  Q("Deep Learning","What is a convolutional neural network (CNN) used for?",["Image and pattern recognition","Text summarization","Audio generation","Data compression"],0,"intermediate"),
  Q("Deep Learning","What is the purpose of pooling layers?",["Reduce spatial dimensions and computation","Add noise","Increase neurons","Normalize input"],0,"intermediate"),
  Q("Deep Learning","What is dropout used for?",["Prevent overfitting","Increase learning rate","Add layers","Reduce epochs"],0,"intermediate"),
  Q("Deep Learning","What is batch normalization?",["Normalizes layer outputs to stabilize learning","Removes data outliers","Adjusts batch size","Tracks loss"],0,"intermediate"),
  Q("Deep Learning","What optimizer adapts learning rates during training?",["RMSprop","Adam","SGD","Adagrad"],1,"intermediate"),
  Q("Deep Learning","What is vanishing gradient problem?",["Gradients become too small for deep layers to update effectively","Gradients explode","Model overfits","Activation fails"],0,"advanced"),
  Q("Deep Learning","What is transfer learning?",["Reusing pre-trained models for similar tasks","Combining multiple models","Duplicating layers","Normalizing inputs"],0,"advanced"),
  Q("Deep Learning","What is ReLU activation function formula?",["f(x) = max(0, x)","f(x) = tanh(x)","f(x) = x²","f(x) = 1 / (1 + e^-x)"],0,"advanced"),
  Q("Deep Learning","What is GAN short for?",["Generative Adversarial Network","Graph Attention Neural","General AI Network","Gradient Adjustment Node"],0,"advanced"),
  Q("Deep Learning","What is gradient clipping used for?",["Prevents exploding gradients by limiting gradient values","Disables dropout","Normalizes input","Speeds up epochs"],0,"advanced"),
  Q("NLP","What is NLP?",["Field of AI that processes and understands human language","Audio compression","Neural network library","Speech recording"],0,"basic"),
  Q("NLP","What does tokenization mean?",["Breaking text into words or sentences","Translating text","Removing stopwords","Encrypting data"],0,"basic"),
  Q("NLP","What are stopwords?",["Common words removed from text like \"and\", \"the\"","Key features","Rare words","Named entities"],0,"basic"),
  Q("NLP","Which library is popular for NLP in Python?",["NLTK","Matplotlib","OpenCV","TensorFlow"],0,"basic"),
  Q("NLP","What is stemming?",["Reducing words to their root form","Expanding contractions","Tagging parts of speech","Counting words"],0,"basic"),
  Q("NLP","What is lemmatization?",["Reducing words to dictionary root with context","Removing punctuation","Translating phrases","Counting words"],0,"intermediate"),
  Q("NLP","What does TF-IDF stand for?",["Term Frequency - Inverse Document Frequency","Term Format - Inverted Dictionary Filter","Token Feature - Information Density Function","Text Function - Index Density Factor"],0,"intermediate"),
  Q("NLP","What is Bag of Words model?",["Represents text as frequency of words ignoring order","Neural network","Vector normalization","Word embedding"],0,"intermediate"),
  Q("NLP","What is named entity recognition (NER)?",["Identifying entities like names, dates, locations","Detecting languages","Translating sentences","Splitting paragraphs"],0,"intermediate"),
  Q("NLP","What is cosine similarity used for?",["Measuring similarity between two text vectors","Tokenizing words","Comparing images","Counting frequency"],0,"intermediate"),
  Q("NLP","What does BERT stand for?",["Bidirectional Encoder Representations from Transformers","Binary Encoder Recurrent Transformer","Balanced Embedding Retrieval Transformer","Bayesian Entity Recognition Technique"],0,"advanced"),
  Q("NLP","What is word embedding?",["Representing words as continuous vector values","Counting words","Grouping documents","Detecting entities"],0,"advanced"),
  Q("NLP","What is sequence-to-sequence model used for?",["Machine translation and text summarization","Classification only","Clustering","Data compression"],0,"advanced"),
  Q("NLP","What is an attention mechanism?",["Allows models to focus on relevant parts of input sequence","Tokenizes faster","Increases layer count","Normalizes embeddings"],0,"advanced"),
  Q("NLP","What is transformer architecture based on?",["Self-attention mechanism","Autoencoders","Convolutional filters","RNN layers"],0,"advanced"),
];

writeFile('aiMlEngineerQuestions.js', 'AI/ML Engineer', ['Python', 'TensorFlow', 'PyTorch', 'Deep Learning', 'NLP'], aiMlEngineerQuestions);

// ROLE 6: CYBERSECURITY SPECIALIST
const cybersecurityQuestions = [
  Q("Network Security","What is the main goal of network security?",["Reducing latency","Protecting data and resources from unauthorized access","Speeding up connections","Increasing bandwidth"],1,"basic"),
  Q("Network Security","What is a firewall?",["Network cable","Device/software that filters incoming and outgoing network traffic","Antivirus program","Backup system"],1,"basic"),
  Q("Network Security","What does VPN stand for?",["Variable Private Net","Verified Proxy Network","Virtual Protected Node","Virtual Private Network"],3,"basic"),
  Q("Network Security","Which protocol is used for secure communication over the internet?",["HTTPS","FTP","Telnet","HTTP"],0,"basic"),
  Q("Network Security","What is an IP address?",["Firewall port","MAC address","Email ID","Unique identifier assigned to each device on a network"],3,"basic"),
  Q("Network Security","What does IDS stand for?",["Intrusion Detection System","Internet Data Storage","Internal Data Server","Integrated Defense Setup"],0,"intermediate"),
  Q("Network Security","What is the purpose of a proxy server?",["Compresses images","Acts as an intermediary between user and internet for security","Manages local devices","Stores encrypted passwords"],1,"intermediate"),
  Q("Network Security","What is port scanning?",["Blocking suspicious users","Encrypting data packets","Rebooting network","Process of finding open ports and services on a system"],3,"intermediate"),
  Q("Network Security","Which layer of the OSI model does a router operate on?",["Data link layer","Transport layer","Session layer","Network layer"],3,"intermediate"),
  Q("Network Security","What is DMZ in networking?",["Domain Master Zone","Direct Memory Zone","Demilitarized Zone — subnetwork that adds extra layer of security","Data Management Zone"],2,"intermediate"),
  Q("Network Security","What is network segmentation?",["Installing multiple routers","Reducing bandwidth","Dividing a network into smaller secure parts","Increasing network range"],2,"advanced"),
  Q("Network Security","What is SSL/TLS used for?",["Encrypting communications between client and server","Monitoring networks","Compressing packets","Managing DNS"],0,"advanced"),
  Q("Network Security","What is ARP spoofing?",["Attack that sends false ARP messages to associate IP with another MAC","DNS lookup","Legal data routing method","IP fragmentation"],0,"advanced"),
  Q("Network Security","What is the main purpose of a honeypot?",["Trap and monitor attackers","Store data","Encrypt passwords","Clean malware"],0,"advanced"),
  Q("Network Security","What is Zero Trust Network?",["Security model assuming no implicit trust; every request is verified","Disabling authentication","VPN tunneling","Public access network"],0,"advanced"),
  Q("Ethical Hacking","What is ethical hacking?",["Authorized attempt to find and fix security vulnerabilities","Virus development","Illegal system access","Cracking passwords"],0,"basic"),
  Q("Ethical Hacking","Ethical hacking is also called?",["Penetration testing","Data mining","Phishing","Spoofing"],0,"basic"),
  Q("Ethical Hacking","Which programming language is widely used for ethical hacking?",["Python","Swift","PHP","Java"],0,"basic"),
  Q("Ethical Hacking","What is footprinting?",["Gathering information about a target system","Changing IP address","Installing antivirus","Encrypting passwords"],0,"basic"),
  Q("Ethical Hacking","What tool is used for network scanning?",["Photoshop","Nmap","Notepad++","MySQL"],1,"basic"),
  Q("Ethical Hacking","What is social engineering?",["Manipulating people to gain confidential info","Network encryption","Malware programming","Security testing"],0,"intermediate"),
  Q("Ethical Hacking","What is vulnerability assessment?",["Identifying weaknesses in systems before attackers exploit them","Installing patches","Rebooting servers","Creating firewalls"],0,"intermediate"),
  Q("Ethical Hacking","What is brute force attack?",["Trying all possible passwords until one works","Guessing one password","Sending viruses","Blocking IPs"],0,"intermediate"),
  Q("Ethical Hacking","Which tool captures network packets?",["Wireshark","Nginx","Chrome DevTools","Jenkins"],0,"intermediate"),
  Q("Ethical Hacking","What is privilege escalation?",["Gaining higher-level access on a system","Adding users","Uploading malware","Deleting backups"],0,"intermediate"),
  Q("Ethical Hacking","What is SQL Injection?",["Exploit where attacker inserts malicious SQL queries","Database backup","Password encryption","Firewall bypass"],0,"advanced"),
  Q("Ethical Hacking","What is XSS (Cross-Site Scripting)?",["Injecting malicious scripts into web pages viewed by users","DNS spoofing","DDoS attack","Cookie deletion"],0,"advanced"),
  Q("Ethical Hacking","What is Metasploit used for?",["Exploitation framework for penetration testing","Logging tool","Packet capture","Virus scanner"],0,"advanced"),
  Q("Ethical Hacking","What is privilege de-escalation?",["Reducing a user's access rights","Increasing privilege level","Closing connections","Exploiting users"],0,"advanced"),
  Q("Ethical Hacking","What is post-exploitation?",["Maintaining access and collecting data after system compromise","Creating firewall","Running initial scan","Stopping logs"],0,"advanced"),
  Q("CISSP","What does CISSP stand for?",["Certified Information Systems Security Professional","Central Information Safety Policy","Cyber Infrastructure Security Specialist Program","Core Internet Security Service Protocol"],0,"basic"),
  Q("CISSP","Which organization manages CISSP certification?",["ISACA","(ISC)²","EC-Council","CompTIA"],1,"basic"),
  Q("CISSP","Which is a fundamental security principle?",["Confidentiality, Integrity, Availability (CIA)","Encrypt, Decrypt, Verify","Speed, Scale, Simplicity","Control, Input, Access"],0,"basic"),
  Q("CISSP","What is least privilege principle?",["Grant only minimum access necessary to perform tasks","Allow public access","Grant admin rights to all users","Disable firewalls"],0,"basic"),
  Q("CISSP","What does risk assessment involve?",["Identifying and evaluating potential security threats","DNS protection","Data encryption","Load testing"],0,"basic"),
  Q("CISSP","What is access control?",["Ensures only authorized users can access resources","Increases speed","Encrypts all data","Monitors server logs"],0,"intermediate"),
  Q("CISSP","What is the main purpose of encryption?",["Protect data confidentiality","Filter traffic","Improve system speed","Reduce bandwidth"],0,"intermediate"),
  Q("CISSP","What is disaster recovery?",["Restoring systems and data after an incident","Encrypting servers","Scanning ports","Updating firmware"],0,"intermediate"),
  Q("CISSP","What is multi-factor authentication?",["Requiring multiple proofs of identity","Captcha verification","Single password access","Disabling login attempts"],0,"intermediate"),
  Q("CISSP","What is the purpose of a security policy?",["Defines rules and practices for data protection","Monitors uptime","Controls marketing data","Sets pricing strategy"],0,"intermediate"),
  Q("CISSP","What is threat modeling?",["Process of identifying, prioritizing, and mitigating potential threats","Creating dummy networks","Simulating firewalls","Writing antivirus"],0,"advanced"),
  Q("CISSP","What is business continuity planning?",["Ensure operations continue during major disruptions","Increase bandwidth","Replace servers","Train developers"],0,"advanced"),
  Q("CISSP","What is defense in depth?",["Using multiple layers of security controls","Encryption only","Single firewall strategy","Disabling users"],0,"advanced"),
  Q("CISSP","What is integrity principle focused on?",["Ensuring data is accurate and unaltered","Backing up files","Hiding data","Limiting access"],0,"advanced"),
  Q("CISSP","What is security auditing?",["Evaluating adherence to security policies and controls","Installing antivirus","Performing backups","Blocking users"],0,"advanced"),
  Q("Penetration Testing","What is the first phase of penetration testing?",["Reconnaissance","Scanning","Exploitation","Reporting"],0,"basic"),
  Q("Penetration Testing","What is a white-box test?",["Tester knows system internals","Tester attacks blindly","Tester has no info","No report phase"],0,"basic"),
  Q("Penetration Testing","What is black-box testing?",["Testing with no internal system knowledge","Static code review","Internal audit","Secure testing"],0,"basic"),
  Q("Penetration Testing","What is a vulnerability?",["Weakness that can be exploited by an attacker","Backup strategy","Firewall rule","API key"],0,"basic"),
  Q("Penetration Testing","What is a payload in penetration testing?",["Code executed on target to gain control","Firewall rule","Data backup","Report summary"],0,"basic"),
  Q("Penetration Testing","What tool is used for web app security testing?",["Jenkins","Burp Suite","Blender","MongoDB"],1,"intermediate"),
  Q("Penetration Testing","What is enumeration?",["Extracting user names, shares, and info from a system","Blocking IPs","Encrypting passwords","Adding logs"],0,"intermediate"),
  Q("Penetration Testing","What is privilege escalation in pentesting?",["Gaining higher access permissions","Rebooting system","Debugging","Network reset"],0,"intermediate"),
  Q("Penetration Testing","What is post-exploitation phase?",["Maintaining access and covering tracks","Cleaning data","Scanning","Gathering logs"],0,"intermediate"),
  Q("Penetration Testing","What does OWASP stand for?",["Open Web Application Security Project","Official Web Audit Security Platform","Open Wide Application Security Protocol","Online Web Application Service Policy"],0,"intermediate"),
  Q("Penetration Testing","What is buffer overflow?",["Exploit where data exceeds memory limit to execute malicious code","Backup failure","File upload issue","API delay"],0,"advanced"),
  Q("Penetration Testing","What is privilege persistence?",["Maintaining admin access over time","Log monitoring","Resetting permissions","File cleanup"],0,"advanced"),
  Q("Penetration Testing","What is shellcode?",["Code injected to open a command shell on victim machine","SQL query","HTML injection","File checksum"],0,"advanced"),
  Q("Penetration Testing","What is lateral movement?",["Moving through a network to access more systems","Updating DNS","Network scanning","Compressing data"],0,"advanced"),
  Q("Penetration Testing","What is fuzzing?",["Automated testing that inputs random data to find vulnerabilities","Encrypting payloads","Generating logs","Bypassing firewalls"],0,"advanced"),
  Q("Cryptography","What is cryptography?",["Practice of securing data by transforming it into unreadable format","Data visualization","File compression","Network routing"],0,"basic"),
  Q("Cryptography","What is plaintext?",["Original unencrypted message","Random text","Encrypted data","Hash code"],0,"basic"),
  Q("Cryptography","What is ciphertext?",["Encrypted version of plaintext","Password key","Plain message","Log entry"],0,"basic"),
  Q("Cryptography","What is encryption key?",["Value used to encode or decode data","Database ID","Token","API string"],0,"basic"),
  Q("Cryptography","What is hashing used for?",["Ensuring data integrity","Backup","Compression","Encryption"],0,"basic"),
  Q("Cryptography","What is symmetric encryption?",["Uses same key for encryption and decryption","Uses two keys","Only hashes data","Changes keys randomly"],0,"intermediate"),
  Q("Cryptography","What is asymmetric encryption?",["Uses public and private key pair","Uses identical keys","Hashes passwords","Compresses data"],0,"intermediate"),
  Q("Cryptography","What algorithm is used in RSA?",["Public key cryptography","Hash chain","Block cipher","Stream cipher"],0,"intermediate"),
  Q("Cryptography","What is AES used for?",["Symmetric key encryption","Hashing passwords","Generating random numbers","Encoding URLs"],0,"intermediate"),
  Q("Cryptography","What is digital signature?",["Used to verify data authenticity and sender identity","Compress files","Encrypt data","Create checksums"],0,"intermediate"),
  Q("Cryptography","What is hashing collision?",["Two inputs produce the same hash output","Encryption failure","Key duplication","Compression conflict"],0,"advanced"),
  Q("Cryptography","What is key exchange protocol?",["Securely sharing encryption keys between parties","Sending data packets","Encoding logs","Resetting passwords"],0,"advanced"),
  Q("Cryptography","What is elliptic curve cryptography (ECC)?",["Efficient public key encryption using elliptic curves","Random key generation","File compression","Hash algorithm"],0,"advanced"),
  Q("Cryptography","What is salting in hashing?",["Adding random data to prevent hash collisions and rainbow attacks","Encoding metadata","Removing duplicates","Compressing input"],0,"advanced"),
  Q("Cryptography","What is SSL certificate used for?",["Securing web communications with encryption","Logging users","Managing domains","Blocking spam"],0,"advanced"),
];

writeFile('cybersecuritySpecialistQuestions.js', 'Cybersecurity Specialist', ['Network Security', 'Ethical Hacking', 'CISSP', 'Penetration Testing', 'Cryptography'], cybersecurityQuestions);

console.log("\n✅ Roles 5-6 complete");
console.log("📊 Progress: 450/600 questions (75%)");
console.log("⏳ Generating final 2 roles...\n");

// ROLE 7: DEVOPS ENGINEER
const devOpsEngineerQuestions = [
  Q("Docker","What is Docker used for?",["Encrypting databases","Writing backend APIs","Designing networks","Containerizing applications to run anywhere"],3,"basic"),
  Q("Docker","What command lists all Docker images?",["docker images","docker view","docker list","docker ps"],0,"basic"),
  Q("Docker","What is a container in Docker?",["A physical server","A virtual network","Lightweight isolated environment for running applications","A compiled binary"],2,"basic"),
  Q("Docker","What file defines a Docker image build process?",["Compose.yml","config.json","Dockerfile","ImageFile"],2,"basic"),
  Q("Docker","What does the docker run command do?",["Deletes all containers","Builds a new image","Creates and starts a new container","Pulls images from registry"],2,"basic"),
  Q("Docker","What is the purpose of Docker Compose?",["Manage multi-container applications","Encrypt images","Create new Dockerfile","Monitor logs"],0,"intermediate"),
  Q("Docker","What is a Docker volume used for?",["Persist data beyond container lifecycle","Store logs","Define networks","Save image layers"],0,"intermediate"),
  Q("Docker","What is Docker Hub?",["Central repository for sharing container images","CLI tool","Network driver","Logging service"],0,"intermediate"),
  Q("Docker","What command removes all stopped containers?",["docker container prune","docker flush","docker reset","docker stop all"],0,"intermediate"),
  Q("Docker","What is a Docker network used for?",["Connecting multiple containers to communicate","Encrypting data","Caching images","Storing logs"],0,"intermediate"),
  Q("Docker","What is a multi-stage build in Docker?",["Process that reduces image size by separating build and runtime stages","Debugging mode","Building multiple images simultaneously","Testing environment"],0,"advanced"),
  Q("Docker","What is the purpose of the ENTRYPOINT command?",["Defines default executable for a container","Installs dependencies","Exports ports","Creates environment variables"],0,"advanced"),
  Q("Docker","What is Docker Swarm?",["Native orchestration tool for clustering containers","Virtual file system","Security layer","Backup system"],0,"advanced"),
  Q("Docker","What does the --detach or -d flag do?",["Runs container in background mode","Builds new image","Removes volumes","Stops container immediately"],0,"advanced"),
  Q("Docker","What is difference between CMD and ENTRYPOINT?",["CMD provides default arguments; ENTRYPOINT defines executable","Both are same","CMD overrides ENTRYPOINT","ENTRYPOINT executes last"],0,"advanced"),
  Q("Kubernetes","Kubernetes is mainly used for?",["Container orchestration and management","CI pipeline setup","Web hosting","Database replication"],0,"basic"),
  Q("Kubernetes","What is a Pod in Kubernetes?",["Smallest deployable unit containing one or more containers","Namespace","Storage volume","Service account"],0,"basic"),
  Q("Kubernetes","What is the command-line tool for Kubernetes?",["kubectl","helm","kubeadm","kubeproxy"],0,"basic"),
  Q("Kubernetes","What is a Node?",["Worker machine that runs Pods","Config file","Log manager","Service mesh"],0,"basic"),
  Q("Kubernetes","What file defines Kubernetes objects?",["YAML file","Config.txt","Dockerfile","JSON file"],0,"basic"),
  Q("Kubernetes","What is a Deployment used for?",["Managing replicas and rollout of Pods","Storing secrets","Monitoring clusters","Creating networks"],0,"intermediate"),
  Q("Kubernetes","What is a ConfigMap?",["Stores non-confidential configuration data","Stores secrets","Defines Pods","Monitors services"],0,"intermediate"),
  Q("Kubernetes","What is a Service in Kubernetes?",["Exposes Pods to network traffic","Scales replicas","Cleans logs","Creates config files"],0,"intermediate"),
  Q("Kubernetes","What does a ReplicaSet do?",["Ensures defined number of Pod replicas are running","Encrypts pods","Monitors metrics","Backups cluster"],0,"intermediate"),
  Q("Kubernetes","What is a Namespace?",["Logical partitioning of cluster resources","Node pool","A network","Pod configuration"],0,"intermediate"),
  Q("Kubernetes","What is Ingress used for?",["Managing external HTTP/HTTPS access to services","Scaling nodes","Load balancing databases","Controlling namespaces"],0,"advanced"),
  Q("Kubernetes","What is etcd in Kubernetes?",["Key-value store maintaining cluster state","DNS resolver","Security scanner","Monitoring tool"],0,"advanced"),
  Q("Kubernetes","What is Helm used for?",["Kubernetes package manager for managing charts","Setting environment variables","Creating Pods manually","Scaling applications"],0,"advanced"),
  Q("Kubernetes","What is kube-scheduler's role?",["Assigns Pods to appropriate Nodes","Cleans namespaces","Restarts services","Monitors API calls"],0,"advanced"),
  Q("Kubernetes","What is the purpose of kube-proxy?",["Handles network traffic routing inside the cluster","Compiles nodes","Encrypts cluster communication","Stores YAML definitions"],0,"advanced"),
  Q("CI/CD","What does CI stand for?",["Continuous Integration","Continuous Improvement","Code Inference","Constant Installation"],0,"basic"),
  Q("CI/CD","What does CD stand for in DevOps?",["Continuous Delivery or Deployment","Continuous Debugging","Command Deployment","Code Design"],0,"basic"),
  Q("CI/CD","What is the main purpose of CI/CD?",["Automate build, test, and deployment processes","Manage API versions","Generate reports","Store code backups"],0,"basic"),
  Q("CI/CD","Which tool is widely used for CI/CD?",["Jenkins","MongoDB","MySQL","Figma"],0,"basic"),
  Q("CI/CD","What is version control used for in CI?",["Tracking code changes and collaboration","Limiting commits","Encrypting repositories","Deleting branches"],0,"basic"),
  Q("CI/CD","What is a build pipeline?",["Automated sequence of steps from code to deployment","Code review","Manual testing","Bug reporting"],0,"intermediate"),
  Q("CI/CD","What is an artifact in CI/CD?",["Compiled or packaged output of a build","Log file","Database table","Configuration file"],0,"intermediate"),
  Q("CI/CD","What is rollback in deployment?",["Reverting to a previous stable version","Undoing commits","Recompiling code","Restarting Jenkins"],0,"intermediate"),
  Q("CI/CD","What is blue-green deployment?",["Zero-downtime release by switching between two environments","Manual deployment","Pipeline scheduling","Testing code in different colors"],0,"intermediate"),
  Q("CI/CD","What is continuous monitoring?",["Tracking application health and performance post-deployment","Running builds repeatedly","Restarting servers","Managing backups"],0,"intermediate"),
  Q("CI/CD","What is canary deployment?",["Releasing updates to small user group before full rollout","Pipeline debugging","Full release at once","Network test"],0,"advanced"),
  Q("CI/CD","What is Infrastructure as Code in CI/CD?",["Managing infrastructure using scripts and version control","Manual provisioning","Hardware monitoring","Software rollback"],0,"advanced"),
  Q("CI/CD","What is pipeline as code?",["Defining CI/CD pipeline configuration using YAML or script files","CI scheduling","Environment cloning","Writing code in pipelines"],0,"advanced"),
  Q("CI/CD","What is container-based deployment?",["Deploying applications in Docker or Kubernetes containers","Offline setup","Manual build","Using cloud only"],0,"advanced"),
  Q("CI/CD","What is DevSecOps?",["Integrating security practices within DevOps pipelines","Security-only deployment","Network testing","Encryption setup"],0,"advanced"),
  Q("Jenkins","Jenkins is a tool for?",["Continuous Integration and Delivery","Database management","Container orchestration","File compression"],0,"basic"),
  Q("Jenkins","Jenkins is written in?",["Java","Python","Go","C++"],0,"basic"),
  Q("Jenkins","What is Jenkinsfile used for?",["Define build pipeline as code","Configure UI","Set passwords","Store logs"],0,"basic"),
  Q("Jenkins","Jenkins plugins are used to?",["Extend Jenkins functionality","Compile source code","Deploy directly to servers","Test APIs"],0,"basic"),
  Q("Jenkins","What is a Jenkins job?",["Task that defines a CI/CD process","Log report","Backup service","User login"],0,"basic"),
  Q("Jenkins","What is a Jenkins agent?",["Node that executes build tasks","Data backup","Web dashboard","Plugin store"],0,"intermediate"),
  Q("Jenkins","What is a pipeline stage?",["Step or group of steps in the build process","Config loader","Job scheduler","Variable file"],0,"intermediate"),
  Q("Jenkins","What is Jenkins master?",["Central controller managing agents","Plugin handler","Backup database","Local worker node"],0,"intermediate"),
  Q("Jenkins","What is Jenkins credential store used for?",["Securely store secrets and API tokens","Encrypt builds","Caching artifacts","Logging users"],0,"intermediate"),
  Q("Jenkins","Which command triggers Jenkins build remotely?",["curl -X POST <job_url>/build","build run","job trigger","jenkins start job"],0,"intermediate"),
  Q("Jenkins","What is Jenkins distributed build?",["Running builds across multiple agents for scalability","Plugin compilation","Sequential tasking","Multi-stage pipeline"],0,"advanced"),
  Q("Jenkins","What is Jenkins Blue Ocean?",["Modern UI for Jenkins pipelines","Plugin management tool","Backup service","Database view"],0,"advanced"),
  Q("Jenkins","What is post-build action?",["Steps executed after a build (e.g., deploy or notify)","Restart Jenkins","Rollback job","Create Dockerfile"],0,"advanced"),
  Q("Jenkins","What is Jenkins shared library?",["Reusable Groovy code library for pipelines","Plugin repository","Worker cache","Secret vault"],0,"advanced"),
  Q("Jenkins","What is Jenkins webhook?",["Automatic trigger from SCM like GitHub when code changes","Manual build","Security test","User login"],0,"advanced"),
  Q("Ansible","Ansible is a tool for?",["Configuration management and automation","File transfer","Code compilation","Cloud hosting"],0,"basic"),
  Q("Ansible","Which language is used to write Ansible playbooks?",["YAML","XML","Bash","JSON"],0,"basic"),
  Q("Ansible","What is an inventory file?",["List of managed hosts for Ansible","Script log","Config cache","Role list"],0,"basic"),
  Q("Ansible","What command runs a playbook?",["ansible-playbook","play start","ansible-run","deploy ansible"],0,"basic"),
  Q("Ansible","What is a module in Ansible?",["Predefined unit that performs specific automation tasks","Playbook header","Config section","YAML comment"],0,"basic"),
  Q("Ansible","What is an Ansible role?",["Organized way to structure reusable automation content","Plugin","User access file","Network setup"],0,"intermediate"),
  Q("Ansible","What is the ad-hoc command format?",["ansible <host> -m <module>","module run ansible","ansible run playbook","ansible task"],0,"intermediate"),
  Q("Ansible","What is idempotency in Ansible?",["Running the same playbook multiple times results in same state","Random execution","Backup process","Scaling tasks"],0,"intermediate"),
  Q("Ansible","What is a handler in Ansible?",["Triggered task that runs when notified by another task","Log reader","Service","User role"],0,"intermediate"),
  Q("Ansible","What does ansible-galaxy do?",["Downloads or shares roles from community repositories","Encrypts files","Runs local scripts","Restarts servers"],0,"intermediate"),
  Q("Ansible","What is Ansible Vault used for?",["Encrypting sensitive data like passwords in playbooks","Monitoring performance","Managing logs","Compressing roles"],0,"advanced"),
  Q("Ansible","What is dynamic inventory?",["Automatically fetches host info from cloud providers","Static host file","Local variable list","API endpoint"],0,"advanced"),
  Q("Ansible","What is Jinja2 in Ansible?",["Template engine used for variable substitution","Logging format","Role manager","Plugin runner"],0,"advanced"),
  Q("Ansible","What is Ansible Tower?",["Web UI and dashboard for managing playbooks and inventories","Command line interface","Database","Monitoring tool"],0,"advanced"),
  Q("Ansible","What is fact gathering?",["Collecting system information from managed hosts","Logging user info","Creating backups","Encrypting playbooks"],0,"advanced"),
];

writeFile('devOpsEngineerQuestions.js', 'DevOps Engineer', ['Docker', 'Kubernetes', 'CI/CD', 'Jenkins', 'Ansible'], devOpsEngineerQuestions);

// ROLE 8: DATA ANALYST
const dataAnalystQuestions = [
  Q("SQL","What does SQL stand for?",["Simple Query Language","Sequential Query Line","System Query Logic","Structured Query Language"],3,"basic"),
  Q("SQL","Which SQL command retrieves data from a table?",["INSERT","DELETE","UPDATE","SELECT"],3,"basic"),
  Q("SQL","Which clause filters rows in SQL?",["GROUP BY","ORDER BY","HAVING","WHERE"],3,"basic"),
  Q("SQL","Which keyword is used to sort results?",["SORT BY","FILTER BY","ORDER BY","RANK BY"],2,"basic"),
  Q("SQL","What is a primary key?",["Duplicate column","Foreign key","Composite field","Unique identifier for each row"],3,"basic"),
  Q("SQL","What is a JOIN used for in SQL?",["Combine rows from two or more tables","Delete rows","Encrypt data","Filter logs"],0,"intermediate"),
  Q("SQL","What does the GROUP BY clause do?",["Sorts rows","Counts columns","Deletes duplicates","Groups rows that have the same values in specified columns"],3,"intermediate"),
  Q("SQL","What is the function to count total rows?",["TOTAL()","SUM()","LEN()","COUNT()"],3,"intermediate"),
  Q("SQL","What is a foreign key?",["Index field","Primary key","Unique constraint","Key that links one table to another"],3,"intermediate"),
  Q("SQL","What is a subquery?",["Temporary table","Query inside another query","Stored procedure","View"],1,"intermediate"),
  Q("SQL","What is a CTE (Common Table Expression)?",["Database function","Stored variable","Schema definition","Temporary named result set within a query"],3,"advanced"),
  Q("SQL","What is an index used for?",["Store metadata","Speed up query performance","Sort data alphabetically","Prevent joins"],1,"advanced"),
  Q("SQL","What is normalization?",["Creating duplicates","Compressing data","Encrypting tables","Organizing data to reduce redundancy"],3,"advanced"),
  Q("SQL","What is the purpose of HAVING clause?",["Sort data","Add constraints","Filter before GROUP BY","Filter results after GROUP BY"],3,"advanced"),
  Q("SQL","What is a stored procedure?",["Data trigger","Precompiled SQL code executed as a program","View generator","Column alias"],1,"advanced"),
  Q("Tableau","Tableau is used for?",["Data visualization and analytics","Cloud storage","Database management","Data encryption"],0,"basic"),
  Q("Tableau","What is a dashboard in Tableau?",["Database schema","Code editor","Report log","Collection of multiple visualizations on one screen"],3,"basic"),
  Q("Tableau","What file type is Tableau Workbook?",[".tvd",".tws",".tbx",".twb"],3,"basic"),
  Q("Tableau","What is a dimension in Tableau?",["Numeric field","Qualitative field (e.g., category, region)","Calculated measure","Metadata field"],1,"basic"),
  Q("Tableau","What is a measure in Tableau?",["Text field","Quantitative value that can be aggregated","Category field","Label"],1,"basic"),
  Q("Tableau","What is a calculated field?",["Hidden variable","Custom field created using formulas","Constant field","Duplicate column"],1,"intermediate"),
  Q("Tableau","What is a story in Tableau?",["Filter type","Data connection","Data source","Sequence of dashboards and sheets that tell insights"],3,"intermediate"),
  Q("Tableau","What is data blending?",["Aggregating data","Sorting dimensions","Filtering outliers","Combining data from multiple sources on different levels"],3,"intermediate"),
  Q("Tableau","What does \"Show Me\" feature do?",["Saves workbooks","Applies filters","Creates dashboards","Suggests chart types based on selected data"],3,"intermediate"),
  Q("Tableau","What is extract in Tableau?",["Local copy of data optimized for performance","External data source","File backup","Log output"],0,"intermediate"),
  Q("Tableau","What is LOD expression?",["Loop on Dimension","Log of Dataset","Local Object Data","Level of Detail — allows calculations at specific data granularity"],3,"advanced"),
  Q("Tableau","What is data densification?",["Filling in missing data points to ensure continuity","Removing duplicates","Compressing extracts","Refreshing metadata"],0,"advanced"),
  Q("Tableau","What is context filter?",["Extract-only filter","Temporary dashboard filter","Hidden filter","Primary filter that sets the basis for dependent filters"],3,"advanced"),
  Q("Tableau","What is parameter in Tableau?",["Chart type","Filter","Field name","Dynamic input value used to replace constant values"],3,"advanced"),
  Q("Tableau","What is dual-axis chart?",["Combines two measures with different scales on one graph","Two dashboards side by side","Scatter plot","Pivot chart"],0,"advanced"),
  Q("Excel","What is Excel primarily used for?",["Data analysis and spreadsheet management","Video editing","3D modeling","Web development"],0,"basic"),
  Q("Excel","What is a cell in Excel?",["Intersection of a row and column","Database table","Chart type","Formula"],0,"basic"),
  Q("Excel","Which function adds numbers in Excel?",["SUM()","ADD()","TOTAL()","PLUS()"],0,"basic"),
  Q("Excel","What does VLOOKUP do?",["Searches for a value in the first column and returns a value from another column","Validates data","Creates charts","Sorts data"],0,"basic"),
  Q("Excel","What is a pivot table?",["Tool for summarizing and analyzing data","Chart type","Formula","Database"],0,"basic"),
  Q("Excel","What is conditional formatting?",["Applies formatting based on cell values","Creates formulas","Imports data","Exports files"],0,"intermediate"),
  Q("Excel","What does the IF function do?",["Returns one value if condition is true, another if false","Adds numbers","Counts cells","Finds text"],0,"intermediate"),
  Q("Excel","What is CONCATENATE used for?",["Joins multiple text strings into one","Splits text","Converts to uppercase","Removes spaces"],0,"intermediate"),
  Q("Excel","What does INDEX-MATCH do?",["Looks up values more flexibly than VLOOKUP","Sorts data","Creates charts","Validates input"],0,"intermediate"),
  Q("Excel","What is data validation?",["Restricts type of data entered in a cell","Creates formulas","Formats cells","Imports data"],0,"intermediate"),
  Q("Excel","What is Power Query?",["Tool for importing and transforming data","Chart creator","Formula builder","Print manager"],0,"advanced"),
  Q("Excel","What are array formulas?",["Formulas that perform multiple calculations on arrays","Simple formulas","Chart formulas","Text formulas"],0,"advanced"),
  Q("Excel","What is Power Pivot?",["Data modeling tool for creating relationships between tables","Chart type","Formula","Macro"],0,"advanced"),
  Q("Excel","What does the OFFSET function do?",["Returns a reference to a range offset from a starting cell","Adds numbers","Counts cells","Formats text"],0,"advanced"),
  Q("Excel","What is a macro in Excel?",["Recorded sequence of commands for automation","Chart type","Formula","Data type"],0,"advanced"),
  Q("Python","What is Python primarily known for?",["Database management","Web design","Hardware programming","Machine learning and scripting"],3,"basic"),
  Q("Python","What symbol is used to start a comment in Python?",["<!--","//","*","#"],3,"basic"),
  Q("Python","Which data type is immutable in Python?",["Dictionary","Set","Tuple","List"],2,"basic"),
  Q("Python","Which keyword defines a function in Python?",["def","define","func","function"],0,"basic"),
  Q("Python","What is the output of len(\"AI\")?",["0","1","3","2"],3,"basic"),
  Q("Python","What is list comprehension used for?",["Declaring arrays","Compressing lists","Sorting dictionaries","Creating new lists in a single line"],3,"intermediate"),
  Q("Python","What does zip() do in Python?",["Compresses files","Combines iterables element-wise into tuples","Encrypts data","Connects databases"],1,"intermediate"),
  Q("Python","Which library is used for numerical computations?",["Pandas","NumPy","Seaborn","Matplotlib"],1,"intermediate"),
  Q("Python","What does try-except handle?",["Loop iteration","Import errors only","Data structures","Exceptions and runtime errors"],3,"intermediate"),
  Q("Python","What is the difference between deepcopy and copy?",["deepcopy duplicates nested objects; copy only references them","deepcopy works only on tuples","Both are same","copy is slower"],0,"intermediate"),
  Q("Python","What is a generator in Python?",["Class constructor","Function that yields values one at a time using yield","Static function","File iterator"],1,"advanced"),
  Q("Python","What is the use of decorators?",["Modify the behavior of functions or methods dynamically","Add HTML tags","Create nested loops","Initialize variables"],0,"advanced"),
  Q("Python","What is the purpose of the @staticmethod decorator?",["Makes method private","Defines a method that does not access class or instance variables","Freezes object attributes","Deletes class instances"],1,"advanced"),
  Q("Python","What is the GIL (Global Interpreter Lock)?",["Mechanism that allows only one thread to execute Python bytecode at a time","Security encryption layer","File system lock","Memory cleaner"],0,"advanced"),
  Q("Python","What does the with open() statement do?",["Deletes file contents","Manages file context automatically (opens and closes safely)","Monitors permissions","Copies files"],1,"advanced"),
  Q("Statistics","What is the mean of [2, 4, 6]?",["3","6","2","4"],3,"basic"),
  Q("Statistics","What is the median of [3, 5, 7, 9, 11]?",["9","5","8","7"],3,"basic"),
  Q("Statistics","What does standard deviation measure?",["The middle value","How spread out data values are from the mean","Frequency","The data range"],1,"basic"),
  Q("Statistics","What is the probability of a coin landing heads?",["0.5","0.25","1.0","0.75"],0,"basic"),
  Q("Statistics","What is mode?",["The most frequently occurring value in a dataset","The average","The smallest number","The largest number"],0,"basic"),
  Q("Statistics","What is a normal distribution?",["A symmetric bell-shaped probability distribution","A binary classifier","A random curve","A skewed histogram"],0,"intermediate"),
  Q("Statistics","What is p-value in hypothesis testing?",["Probability of obtaining results by chance","Mean of dataset","Significance level","Population size"],0,"intermediate"),
  Q("Statistics","What is correlation?",["Measure of relationship strength between two variables","Error in data","Difference between means","Type of average"],0,"intermediate"),
  Q("Statistics","What is variance?",["Data maximum","Frequency count","Ratio of probabilities","Average of squared differences from the mean"],3,"intermediate"),
  Q("Statistics","What is confidence interval?",["Range likely to contain true population parameter","Mode range","Standard error","Confidence score"],0,"intermediate"),
  Q("Statistics","What does the central limit theorem state?",["Sampling distribution of mean approaches normal as sample size increases","Mean and median are always equal","All datasets are normally distributed","Variance always decreases with more samples"],0,"advanced"),
  Q("Statistics","What is multicollinearity?",["High correlation among independent variables","Missing data in regression","Nonlinear trends","Data duplication"],0,"advanced"),
  Q("Statistics","What is Type I error?",["Rejecting a true null hypothesis","Accepting a false null hypothesis","Failing to detect a difference","Wrongly classifying an observation"],0,"advanced"),
  Q("Statistics","What is a chi-square test used for?",["Testing independence between categorical variables","Regression fitting","Calculating mean difference","Data normalization"],0,"advanced"),
  Q("Statistics","What is the null hypothesis (H₀)?",["Assumes no effect or no difference exists","Assumes relationship exists","Predicts variance increase","Always false"],0,"advanced"),
];

writeFile('dataAnalystQuestions.js', 'Data Analyst', ['SQL', 'Tableau', 'Excel', 'Python', 'Statistics'], dataAnalystQuestions);

console.log("\n🎉🎉🎉 ALL 600 QUESTIONS GENERATED! 🎉🎉🎉");
console.log("=".repeat(50));
console.log("✅ Role 1: Full Stack Developer - 75 questions");
console.log("✅ Role 2: Data Scientist - 75 questions");
console.log("✅ Role 3: Cloud Engineer - 75 questions");
console.log("✅ Role 4: Mobile Developer - 75 questions");
console.log("✅ Role 5: AI/ML Engineer - 75 questions");
console.log("✅ Role 6: Cybersecurity Specialist - 75 questions");
console.log("✅ Role 7: DevOps Engineer - 75 questions");
console.log("✅ Role 8: Data Analyst - 75 questions");
console.log("=".repeat(50));
console.log("\n📊 Total: 600/600 questions (100%)");
console.log("\n🚀 Next step: Run the seed script to import all questions!");
console.log("   Command: node src/scripts/seedAllQuestions.js\n");
